### ISSUE TITLE
won a bid?

### ISSUE THREAD

**Issue by asulwer** [melikpehlivanov/AuctionSystem#275]
no notification when a bid is won?  also need a page listing current bids and past wins/losses

**Comment by melikpehlivanov** [comment]
Hello, @asulwer. I tested the application and notifications work properly. Probably something with your sendgrid configuration is not correct. And about your second suggestion - yeah, I already know that these 'pages' should be implemented but currently the project is not in active development and I don't have any idea when I'm going to implement these pages and it's not only these two pages, there is a lot of stuff which can be added and improved but for now I'll leave it as it is.

Thank you!

**Comment by melikpehlivanov** [comment]
Hello, @asulwer. I tested the application and notifications work properly. Probably something with your sendgrid configuration is not correct. And about your second suggestion - yeah, I know that these 'pages' should be implemented but currently the project is not in active development and I don't have any idea when I'm going to implement these pages and it's not only these two pages, there is a lot of stuff which can be added and improved but for now I'll leave it as it is.

Thank you for your time and understanding!

**Comment by asulwer** [comment]
send me a list of areas to work on.  i see merit with this system and will actively use it.  i restructured the solution. removed support for Cloudinary in favor of a url link, this is specific for my use

**Comment by melikpehlivanov** [comment]
Hey, again @asulwer. Thank you for your interest in this project. You can fork the project and make local changes.
